### ISSUE TITLE
Got erros when getting dataset from generate_dcase_tast4_2021 and during training

### ISSUE THREAD

**Issue by Lilac-wgk** [DCASE-REPO/DESED_task#17]
Hi, I got two erros when running the file [generate_dcase_task4_2021.py] and [train_sed.py]

1. There's an error "shut.ReadError: ~/DESED_task-master/recipes/dcase2021_task4baseline/tmp_88czbqta/tmpct_t19xo..zip is not a zip file" when run the generate_dcase_task4_2021.py

2. There's an error like

Traceback (most recent call last):
  File "generate_dcase_task4_2021.py", line 794, in <module>
    generate_soundscapes(
  File "generate_dcase_task4_2021.py", line 571, in generate_soundscapes
    events = instantiate_soundscape(
  File "generate_dcase_task4_2021.py", line 422, in instantiate_soundscape
    sc = add_bg(sc)
  File "generate_dcase_task4_2021.py", line 343, in add_bg
    bg_instance = sc._instantiate()["annotations"][0]["data"][0][2]
  File "/home/gook/miniconda3/lib/python3.8/site-packages/scaper/core.py", line 1712, in _instantiate
    value = self._instantiate_event(
  File "/home/gook/miniconda3/lib/python3.8/site-packages/scaper/core.py", line 1426, in _instantiate_event
    label = _get_value_from_dist(label_tuple, self.random_state)
  File "/home/gook/miniconda3/lib/python3.8/site-packages/scaper/core.py", line 424, in _get_value_from_dist
    return SUPPORTED_DIST[dist_tuple[0]](*dist_tuple[1:], random_state=random_state)
  File "/home/gook/miniconda3/lib/python3.8/site-packages/scaper/util.py", line 270, in _sample_choose
    index = random_state.randint(len(new_list_of_options))
  File "mtrand.pyx", line 746, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1254, in numpy.random._bounded_integers._rand_int64
ValueError: low >= high

when run the generate_dcase_task4_2021.py again (got error 1 and run again)

3. when run the train_sed.py in this state, there is an error message "No File or Directory /DESED_task-master/data/raw_datasets/desed_real/metadata/validation/duration.tsv"

Is there any way to fix those bugs?

**Comment by turpaultn** [comment]
Hi, 
1. Could you remove `~/DESED_task-master/recipes/dcase2021_task4baseline/tmp_88czbqta` please ? 
2. This means you have a background folder which is empty, I suspect it is due to SINS not well downloaded (go check in the `raw_dataset/desed` folder inside background). 
3. This means there was indeed a problem during data download, and you did not download real data yet (no metadata, so I suppose neither the audio)

First thing would be to check if the problem is actually coming from SINS. (You could try to remove the `data` folder and retry first)

**Comment by turpaultn** [comment]
Did you have time to check it or solve your problem ?

**Comment by gook-won** [comment]
Oh, yes but it still has error, so I downloaded datasets through Zenodo😅. Thanks for your kind :)
