### ISSUE TITLE
Got error while running the training script for SED

### ISSUE THREAD

**Issue by suhasineejain** [DCASE-REPO/DESED_task#18]
Hello, I got the following error while trying to train the model by running 'train_sed.py'. 

Epoch 0:   0%|                                                                                                                      | 0/229 [00:00<?, ?it/s]/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/torch/functional.py:515: UserWarning: stft will require the return_complex parameter be explicitly  specified in a future PyTorch release. Use return_complex=False  to preserve the current behavior or return_complex=True to return  a complex output. (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729009598/work/aten/src/ATen/native/SpectralOps.cpp:653.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore
/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/torch/functional.py:515: UserWarning: The function torch.rfft is deprecated and will be removed in a future PyTorch release. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.fft or torch.fft.rfft. (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729009598/work/aten/src/ATen/native/SpectralOps.cpp:590.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore
Epoch 0:  97%|▉| 222/229 [01:24<00:02,  2.62it/s, loss=1.21, v_num=3, train/step=117.0, train/student/tot_self_loss=3.47e-5, train/student/tot_supervised=0Traceback (most recent call last):██████████████████████████████████████████████████████████████████████████████████▍      | 104/111 [00:18<00:01,  5.92it/s]
  File "train_sed.py", line 295, in <module>
    single_run(
  File "train_sed.py", line 244, in single_run
    trainer.fit(desed_training)
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run
    self.dispatch()
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 797, in dispatch
    self.accelerator.start_training(self)
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 807, in run_stage
    return self.run_train()
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 869, in run_train
    self.train_loop.run_training_epoch()
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 576, in run_training_epoch
    self.trainer.run_evaluation(on_epoch=True)
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 962, in run_evaluation
    output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 174, in evaluation_step
    output = self.trainer.accelerator.validation_step(args)
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 226, in validation_step
    return self.training_type_plugin.validation_step(*args)
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/home/SharedData/Suhasinee/DESED_task-master/recipes/dcase2021_task4_baseline/local/sed_trainer.py", line 371, in validation_step
    self.get_weak_student_f1_seg_macro(
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/torchmetrics/metric.py", line 168, in forward
    self.update(*args, **kwargs)
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/torchmetrics/metric.py", line 216, in wrapped_func
    return update(*args, **kwargs)
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/torchmetrics/classification/stat_scores.py", line 207, in update
    tp, fp, tn, fn = _stat_scores_update(
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/torchmetrics/functional/classification/stat_scores.py", line 90, in _stat_scores_update
    preds, target, _ = _input_format_classification(
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/torchmetrics/utilities/checks.py", line 418, in _input_format_classification
    case = _check_classification_inputs(
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/torchmetrics/utilities/checks.py", line 268, in _check_classification_inputs
    _basic_input_validation(preds, target, threshold, multiclass)
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/torchmetrics/utilities/checks.py", line 36, in _basic_input_validation
    raise ValueError("The `target` has to be an integer tensor.")
ValueError: The `target` has to be an integer tensor.
Exception ignored in: <function tqdm.__del__ at 0x7f85288df160>
Traceback (most recent call last):
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/tqdm/std.py", line 1145, in __del__
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/tqdm/std.py", line 1299, in close
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/tqdm/std.py", line 1492, in display
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __str__
  File "/nfs4/suhasinee/miniconda3/envs/dcase2021/lib/python3.8/site-packages/tqdm/std.py", line 1450, in format_dict
TypeError: cannot unpack non-iterable NoneType object

Please suggest on how to fix this issue.

**Comment by suhasineejain** [comment]
In the python script 'sed_trainer.py' in the local folder, in line 247 'labels_weak' have been converted to float datatype which throws an error in line 375
self.get_weak_student_f1_seg_macro( weak_preds_student[mask_weak], labels_weak)
ValueError: The target has to be an integer tensor.

So I simply changed the datatype of 'labels_weak' back to int in line 375 and 378 by doing labels_weak.int() and that got me rid of the error.
