### ISSUE TITLE
Unidentified Symbol error when running train_sed.py

### ISSUE THREAD

**Issue by khantildesai** [DCASE-REPO/DESED_task#19]
I used to have issues running generate_dcase_task4_2021.py, but fixed it using by doing this:
import desed
desed.download.filter_sins("PATH/TO/DCASE2018-task5-dev",  destination_folder=os.path.join("PATH/TO/background", "sins"),
    classes_kept=["other"],
    rm_original_sins=True)

however, after running generate_dcase_task4_2021.py, I now get this error when trying to run train_sed.py:
Traceback (most recent call last):
  File "train_sed.py", line 17, in <module>
    from desed_task.utils.encoder import ManyHotEncoder
  File "/media/roestlab/Data3/User/LeonX/github/DESED_task/desed_task/utils/__init__.py", line 2, in <module>
    from .schedulers import ExponentialWarmup
  File "/media/roestlab/Data3/User/LeonX/github/DESED_task/desed_task/utils/schedulers.py", line 1, in <module>
    from asteroid.engine.schedulers import *
  File "/home/roestlab/anaconda3/envs/dcase2021/lib/python3.8/site-packages/asteroid/__init__.py", line 3, in <module>
    from .models import ConvTasNet, DCCRNet, DCUNet, DPRNNTasNet, DPTNet, LSTMTasNet, DeMask
  File "/home/roestlab/anaconda3/envs/dcase2021/lib/python3.8/site-packages/asteroid/models/__init__.py", line 2, in <module>
    from .base_models import BaseModel
  File "/home/roestlab/anaconda3/envs/dcase2021/lib/python3.8/site-packages/asteroid/models/base_models.py", line 4, in <module>
    from .. import separate
  File "/home/roestlab/anaconda3/envs/dcase2021/lib/python3.8/site-packages/asteroid/separate.py", line 14, in <module>
    from .dsp.overlap_add import LambdaOverlapAdd
  File "/home/roestlab/anaconda3/envs/dcase2021/lib/python3.8/site-packages/asteroid/dsp/__init__.py", line 2, in <module>
    from .overlap_add import LambdaOverlapAdd, DualPathProcessing
  File "/home/roestlab/anaconda3/envs/dcase2021/lib/python3.8/site-packages/asteroid/dsp/overlap_add.py", line 3, in <module>
    from ..losses.pit_wrapper import PITReorder
  File "/home/roestlab/anaconda3/envs/dcase2021/lib/python3.8/site-packages/asteroid/losses/__init__.py", line 14, in <module>
    from .stoi import NegSTOILoss as SingleSrcNegSTOI
  File "/home/roestlab/anaconda3/envs/dcase2021/lib/python3.8/site-packages/asteroid/losses/stoi.py", line 5, in <module>
    from torch_stoi import NegSTOILoss as _NegSTOILoss
  File "/home/roestlab/anaconda3/envs/dcase2021/lib/python3.8/site-packages/torch_stoi/__init__.py", line 1, in <module>
    from .stoi import NegSTOILoss
  File "/home/roestlab/anaconda3/envs/dcase2021/lib/python3.8/site-packages/torch_stoi/stoi.py", line 5, in <module>
    import torchaudio
  File "/home/roestlab/anaconda3/envs/dcase2021/lib/python3.8/site-packages/torchaudio/__init__.py", line 1, in <module>
    from . import extension
  File "/home/roestlab/anaconda3/envs/dcase2021/lib/python3.8/site-packages/torchaudio/extension/__init__.py", line 5, in <module>
    _init_extension()
  File "/home/roestlab/anaconda3/envs/dcase2021/lib/python3.8/site-packages/torchaudio/extension/extension.py", line 12, in _init_extension
    _init_script_module(ext)
  File "/home/roestlab/anaconda3/envs/dcase2021/lib/python3.8/site-packages/torchaudio/extension/extension.py", line 19, in _init_script_module
    torch.classes.load_library(path)
  File "/home/roestlab/anaconda3/envs/dcase2021/lib/python3.8/site-packages/torch/_classes.py", line 46, in load_library
    torch.ops.load_library(path)
  File "/home/roestlab/anaconda3/envs/dcase2021/lib/python3.8/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/home/roestlab/anaconda3/envs/dcase2021/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/roestlab/anaconda3/envs/dcase2021/lib/python3.8/site-packages/torchaudio/_torchaudio.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtESt10shared_ptrIS0_EPSo

I tried to delete all the symlinks and re-run generate_dcase_task4_2021.py but still get this error when trying to run train_sed.py .

**Comment by turpaultn** [comment]
Did you succeed to solve your problem ?
