### ISSUE TITLE
Error torchmetrics in recipes dcase_2022

### ISSUE THREAD

**Issue by turpaultn** [DCASE-REPO/DESED_task#47]
When launching the baseline at test, I get this error: 
```
loaded model: epoch=156-step=18525.ckpt?download=1
at epoch: 157
Global seed set to 42
Traceback (most recent call last):
  File "train_sed.py", line 377, in <module>
    single_run(
  File "train_sed.py", line 228, in single_run
    desed_training = SEDTask4(
  File "/projects/pul51/shared/calcul/users/nturpault/DESED_task/recipes/dcase2022_task4_baseline/local/sed_trainer.py", line 122, in __init__
    self.get_weak_teacher_f1_seg_macro = torchmetrics.classification.f_beta.F1(
AttributeError: module 'torchmetrics.classification.f_beta' has no attribute 'F1'
```
I have run the conda_create_environment from the recipe, am I the only one to get this ?

**Comment by RonFrancesca** [comment]
Hi @turpaultn, 

you should use the version torchmetrics==0.7.3.

**Comment by turpaultn** [comment]
It is not in any requirement, I'll do a pull request ;)
