### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\xef'.

### ISSUE THREAD

**Issue by SevenKkkkkkk** [DCASE-REPO/DESED_task#94]
An error occurred while running recipes/dcase2024_task4_baseline/extract_embeddings. py

Skipping download as file in ./pretrained_models/BEATS_iter3_plus_AS2M.pt exists already
Traceback (most recent call last):
  File "/home/dl/data/DESED_task-master/recipes/dcase2024_task4_baseline/extract_embeddings.py", line 189, in <module>
    pretrained = BEATsModel(cfg_path="./pretrained_models/BEATS_iter3_plus_AS2M.pt")
  File "/home/dl/data/DESED_task-master/recipes/dcase2024_task4_baseline/local/beats/BEATs.py", line 194, in __init__
    checkpoint = torch.load(cfg_path)
  File "/home/dl/anaconda3/envs/dcase2024/lib/python3.8/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/dl/anaconda3/envs/dcase2024/lib/python3.8/site-packages/torch/serialization.py", line 1262, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xef'.

**Comment by popcornell** [comment]
Can you retry and recompute them ? 
It could be that some dumped embeddings got corrupted

**Comment by SevenKkkkkkk** [comment]
谢谢你，解决了，是利用extract_embeddings. py代码直接下载的BEATs_iter3_plus_AS2M.pt文件有问题，我直接去BEATs源代码那里下载了，然后就解决啦（https://github.com/microsoft/unilm/tree/master/beats）
